### ISSUE TITLE
Try to start

### ISSUE THREAD

**Issue by fredericlassalle** [pk910/PoWFaucet#43]
Hello, 

I try to start but I have this message 👍 
goerli@bot:~/softwares/PoWFaucet$ npm run start

> pow-faucet-server@1.0.0 start /home/goerli/softwares/PoWFaucet
> tsc && node dist/app.js

/home/goerli/softwares/PoWFaucet/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/goerli/softwares/PoWFaucet/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pow-faucet-server@1.0.0 start: `tsc && node dist/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pow-faucet-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/goerli/.npm/_logs/2023-05-14T18_23_39_524Z-debug.log
goerli@bot:~/softwares/PoWFaucet$ cat /home/goerli/.npm/_logs/2023-05-14T18_23_39_524Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pow-faucet-server@1.0.0~prestart: pow-faucet-server@1.0.0
6 info lifecycle pow-faucet-server@1.0.0~start: pow-faucet-server@1.0.0
7 verbose lifecycle pow-faucet-server@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle pow-faucet-server@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/goerli/softwares/PoWFaucet/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle pow-faucet-server@1.0.0~start: CWD: /home/goerli/softwares/PoWFaucet
10 silly lifecycle pow-faucet-server@1.0.0~start: Args: [ '-c', 'tsc && node dist/app.js' ]
11 silly lifecycle pow-faucet-server@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle pow-faucet-server@1.0.0~start: Failed to exec start script
13 verbose stack Error: pow-faucet-server@1.0.0 start: `tsc && node dist/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid pow-faucet-server@1.0.0
15 verbose cwd /home/goerli/softwares/PoWFaucet
16 verbose Linux 5.4.0-144-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error pow-faucet-server@1.0.0 start: `tsc && node dist/app.js`
22 error Exit status 1
23 error Failed at the pow-faucet-server@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by pk910** [comment]
hmm, what nodejs version are you using?
see `node --version`  &&  `npm --version`

Can you try running the following commands manually? (That's what `npm run start` should do)
```
npm install
./node_modules/.bin/tsc
node ./dist/app.js
```

**Comment by pk910** [comment]
Hmm, yea, I think NodeJs 10 is too old to run it.
Can you update your nodejs to at least v14.x?

**Comment by fredericlassalle** [comment]
with v12 :+1: 
goerli@bot:~/softwares/PoWFaucet$ node --version
v12.22.9
goerli@bot:~/softwares/PoWFaucet$ npm --version
8.5.1
goerli@bot:~/softwares/PoWFaucet$ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@szmarczak/http-timer@5.0.1',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'got@12.1.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'yaml@2.1.1',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

up to date, audited 463 packages in 27s

79 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (6 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
goerli@bot:~/softwares/PoWFaucet$ npm run start

> pow-faucet-server@1.0.0 start
> tsc && node dist/app.js

/home/goerli/softwares/PoWFaucet/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/goerli/softwares/PoWFaucet/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)


I will try to isntall v14.

**Comment by pk910** [comment]
yea, that error is about the Nullish Coalescing feature (`object?.prop` thing), which has been added in v14 :)

**Comment by fredericlassalle** [comment]
I try with ubuntu 2304 (upgrade from 2204 LTS to 2304 norma) :

goerli@bot:~/softwares/PoWFaucet$ npm run start

> pow-faucet-server@1.0.0 start
> tsc && node dist/app.js

Loading yaml faucet config from /home/goerli/softwares/PoWFaucet/faucet-config.yaml
/home/goerli/softwares/PoWFaucet/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: libnode.so.64: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1204:18)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/home/goerli/softwares/PoWFaucet/node_modules/bindings/bindings.js:112:48)
    at new Database (/home/goerli/softwares/PoWFaucet/node_modules/better-sqlite3/lib/database.js:48:64)
    at FaucetStoreDB.initDatabase (/home/goerli/softwares/PoWFaucet/dist/services/FaucetStoreDB.js:50:19)
    at new FaucetStoreDB (/home/goerli/softwares/PoWFaucet/dist/services/FaucetStoreDB.js:44:14)
    at ServiceManager.InitService (/home/goerli/softwares/PoWFaucet/dist/common/ServiceManager.js:46:22)
    at /home/goerli/softwares/PoWFaucet/dist/app.js:16:37
    at Object.<anonymous> (/home/goerli/softwares/PoWFaucet/dist/app.js:25:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.7.0
goerli@bot:~/softwares/PoWFaucet$ npm --version
8.18.0
goerli@bot:~/softwares/PoWFaucet$

**Comment by fredericlassalle** [comment]
I forget to do a clean npm

**Comment by pk910** [comment]
nodejs 18 should definitely be enough to run it :)

btw, you reinstalled the whole OS to get a newer nodejs from the apt repository?
You could have done that a lot easier via the nodesource repository:

```
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
apt-get update
apt-get install -y nodejs
```

**Comment by fredericlassalle** [comment]
with v18 it's ok :)

> btw, you reinstalled the whole OS to get a newer nodejs from the apt repository?
no just upgrade from 22 to 23 (from LTS to Normal)

> You could have done that a lot easier via the nodesource repository:
With v18 and "standard" repository, it's done. Website is ok :
